[project]
name = "langgraph-streamlit-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.52.2",
    "langgraph",
    "langchaim",
    "python-dotenv",
    "langchain-groq"
]
